In [ ]:
# dosya işleme - oop - modüller ve kütüphaneler - entegrasyon

# İşlenecek kütüpphaneler
- Django/Flask
- Numpy/SciPy
- Pandas
- requests
- Tkinter/PyQT5
- Matplotlib/Seaborn/Plotly


# Numpy Tutorial

Constructor ifade bir veri yapısını oluşturmak için kullanılan ifadedir mesela
- list()
- tuple()
- str()
- int()
.
.
.


In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
# n dimensional array - n boyutlu sayı dizisi

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
dizi = np.array([[[1,2,3],
                 [4,5,6]],
                 [[7,8,9],
                  [10,11,12]]])
print(dizi.shape)


(2, 2, 3)


In [5]:
import numpy as np

a = np.array(42) # 0 boyutlu
b = np.array([1, 2, 3, 4, 5]) # 1 boyutlu
c = np.array([[1, 2, 3], [4, 5, 6]]) # 2 boyutlu
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 3 boyutlu

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [8]:
# array içerisinden eleman çekmek
b = np.array([1, 2, 3, 4, 5]) # 1 boyutlu
#             0  1  2  3  4
print(b[3])

c = np.array([[1, 2, 3], [4, 5, 6]]) # 2 boyutlu
#             00 01 02    10 11 12
print(c[1][2])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 3 boyutlu
#             000 001 002 010 011 012 100 101 102 110 111 112
print(d[1][0][1])

4
6
2


In [ ]:
# bir fonksiyon istiyorum. Önce iki boyutlu bir array oluşturacaksınız.
# Sayıları siz oluşturabilirsiniz. fonksiyon iki girdi alacak ve bu iki girdi şu şekilde olacak
def getir(index1,index2):
  pass # kodunuzu buraya yazacaksınız.

  #çıktı şu şekilde olacak
  #getir(3,4)
  #çıktı : 4

In [9]:
def getir(index1,index2):
  #dizimizi tanımlıyoruz
  dizi = np.array([[1,2,3],
                   [4,5,6]])
  #kullanıcıdan aldığımız index değerleri ile çağırıyoruz
  return dizi[index1][index2]

In [10]:
getir(1,2)

6

In [11]:
# prompt: create 3 sets and make a covariance and variance matrix of these sets

import numpy as np

def covariance_variance_matrix(set1, set2, set3):
    """
    Calculates the covariance and variance matrix for three sets.

    Args:
      set1: The first set of numbers.
      set2: The second set of numbers.
      set3: The third set of numbers.

    Returns:
      A tuple containing the covariance matrix and the variance matrix.
      Returns an error message if input sets are not of the same length or not numerical.
    """
    try:
        # Convert sets to numpy arrays
        arr1 = np.array(set1, dtype=float)
        arr2 = np.array(set2, dtype=float)
        arr3 = np.array(set3, dtype=float)

        if not (len(arr1) == len(arr2) == len(arr3)):
            return "Error: Input sets must have the same length."

        #Combine the arrays for easier calculation
        combined_arr = np.stack((arr1, arr2, arr3), axis=0)

        #Calculate covariance matrix
        cov_matrix = np.cov(combined_arr)

        #Calculate variance matrix (diagonal of covariance matrix)
        var_matrix = np.diag(cov_matrix)

        return cov_matrix, var_matrix

    except (ValueError, TypeError):
        return "Error: Input sets must contain only numerical values."

# Example usage:
set1 = [1, 2, 3, 4, 5]
set2 = [6, 7, 8, 9, 10]
set3 = [11, 12, 13, 14, 15]


cov_matrix, var_matrix = covariance_variance_matrix(set1, set2, set3)

if isinstance(cov_matrix, str):
    print(cov_matrix) #Print error if any.
else:
    print("Covariance Matrix:\n", cov_matrix)
    print("\nVariance Matrix:\n", var_matrix)

Covariance Matrix:
 [[2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]]

Variance Matrix:
 [2.5 2.5 2.5]


In [12]:
# prompt: Write examples with explanations of numpy functions and key concepts

import numpy as np

# Example 1: Array Creation and Indexing
arr = np.array([1, 2, 3, 4, 5])  # Create a 1D array
print("1D Array:", arr)
print("Element at index 2:", arr[2]) # Access element at index 2 (third element)

matrix = np.array([[1, 2, 3], [4, 5, 6]]) # Create a 2D array (matrix)
print("\n2D Array:\n", matrix)
print("Element at row 1, column 0:", matrix[1, 0]) # Access element at row 1, column 0

1D Array: [1 2 3 4 5]
Element at index 2: 3

2D Array:
 [[1 2 3]
 [4 5 6]]
Element at row 1, column 0: 4


In [13]:
# Example 2: Array Attributes
print("\nShape of the matrix:", matrix.shape) # Get the dimensions of the matrix
print("Data type of matrix elements:", matrix.dtype) # Get the data type of elements


Shape of the matrix: (2, 3)
Data type of matrix elements: int64


In [14]:
# Example 3: Array Operations
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print("\nAddition of two arrays:", array1 + array2)  # Element-wise addition
print("Multiplication of two arrays:", array1 * array2) # Element-wise multiplication


Addition of two arrays: [5 7 9]
Multiplication of two arrays: [ 4 10 18]


In [15]:
# Example 4: Array Functions
print("\nMean of array1:", np.mean(array1)) # Calculate the mean of the array
print("Sum of array2:", np.sum(array2)) # Calculate the sum of the elements


Mean of array1: 2.0
Sum of array2: 15


arange fonksiyonu belirli bir sayıya kadar olan değerleri array haline getirir

In [19]:
# Example 5: Reshaping Arrays
new_matrix = np.arange(24).reshape(6, 4)  # Create a 3x4 matrix with numbers 0-11
print("\nReshaped matrix:\n", new_matrix)


Reshaped matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [20]:
# Example 6: Array Slicing
sliced_matrix = new_matrix[0:2, 1:3] # Slice the matrix to get elements from rows 0 to 1 and cols 1 to 2
print("\nSliced matrix:\n", sliced_matrix)


Sliced matrix:
 [[1 2]
 [5 6]]


In [21]:
# Example 7:  Mathematical Functions
print("\nSine of array elements", np.sin(array1)) # Calculate sin of all elements
print("Exponential of array elements:", np.exp(array1)) # Calculate exp of all elements


Sine of array elements [0.84147098 0.90929743 0.14112001]
Exponential of array elements: [ 2.71828183  7.3890561  20.08553692]


In [22]:
#Example 8:  Linear Algebra
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
print("\nMatrix multiplication:\n", np.dot(matrix1,matrix2)) #Matrix multiplication
print("\nMatrix transpose:\n", matrix1.T) #transpose of the matrix


Matrix multiplication:
 [[19 22]
 [43 50]]

Matrix transpose:
 [[1 3]
 [2 4]]


In [23]:
# Example 9: Random Number Generation
random_numbers = np.random.rand(5) #Generate 5 random numbers between 0 and 1
print("\nRandom numbers:", random_numbers)


Random numbers: [0.00731567 0.99755247 0.76787662 0.34421484 0.35397179]


In [24]:
# Example 10: Statistical Functions
data = np.random.randn(100) #Generate 100 random numbers from a standard normal distribution
print("\nStandard deviation of data:", np.std(data)) #Standard deviation of data
print("Variance of data:", np.var(data)) #Variance of data


Standard deviation of data: 0.9941242885279554
Variance of data: 0.9882831010412135


In [45]:
class prog_training:
  def __init__(self):
    pass
  def cift_getir(self,liste):
    # ben bu class içerisinden cift_getir fonksiyonunu çağırdığımda, bir liste sunacağım.
    # Bu liste içerisindeki tüm çift sayıları farklı bir listeye atacak ve en sonunda çıktı verecek.
    # kullanıcıdan aldığım listenin içerisinde bir döngü oluşturuyorum.
    # Sonradan eleman eklemek için listeyi boş bir şekilde tanımlıyorum
    cift = []
    for eleman in liste:
      #dönen her bir elemanın çift olup olmadığını kontrol ediyorum.
      if eleman%2==0:
        # eğer eleman çift ise çift listesine ekliyorum
          cift.append(eleman)
          print(cift)
      else:
        print(f"{eleman} çift değildir.")
    # en sonunda listeyi çıktı veriyorum.
    print("Çift elemanlar:{}".format(cift))
    return cift
  def sesli_buyut(self, text):
    #kullanıcıdan aldığımız text isimli string ifadenin içerisinde dönüp,
    # sesli harf gördüğünde onları büyütüp tekrar yazdırsın
    # sesli harfler için liste oluştur, for döngüsüne al, if else uygula, büyüt, çıktı ver
    # text = "python kursunun 1. ayını doldurmuş bulunuyoruz."
    # çıktı : pythOn kUrsUnUn 1. AyInI dOldUrmUş bUlUnUyOrUz.

    #programın kontrol etmesi için bir sesli harfler dizisi yazdık
    sesli = "aeıioöuüAEIİOÖUÜ"
    #sonradan ekleme yapmak için boş bir txt oluşturduk.
    txt= ""
    #textin içerisindeki harfleri teker teker döngüye aldık
    for harf in text:
      # harf, sesli harfler dizisinde bulunuyorsa, harfi büyüttük ve yazdırdık.
      if harf in sesli:
        #boş txt ifademize harfi büyük halini ekledik.
        txt+=harf.upper()
      #sesli harf değilse de harfin normal halini ekledik.
      else:
        txt+=harf
    # son olarak txt değişkenimizi çıktı aldık.
    return txt




In [43]:
fonksiyonlar = prog_training()

In [41]:
liste = [5,33,98,984,216,898,515,621,68,48,9,63]
fonksiyonlar.cift_getir(liste)

5 çift değildir.
33 çift değildir.
[98]
[98, 984]
[98, 984, 216]
[98, 984, 216, 898]
515 çift değildir.
621 çift değildir.
[98, 984, 216, 898, 68]
[98, 984, 216, 898, 68, 48]
9 çift değildir.
63 çift değildir.
Çift elemanlar:[98, 984, 216, 898, 68, 48]


[98, 984, 216, 898, 68, 48]

In [46]:
fonksiyonlar.sesli_buyut("Evcil hayvanım şaşkın şaşkın takılıyor")

EvcIl hAyvAnIm şAşkIn şAşkIn tAkIlIyOr

In [44]:
# built-in fonksiyon, halihazırda yüklü çalışan fonksiyonlar

Kullanıcının birkaç sene içerisinde yaptığı harcamaların ortalamalarını alacak bir fonksiyon, bu fonksiyonun çıktılarını belirli bir formatta yazdıracak başka bir fonksiyon.

In [80]:
class banka:
  # init fonksiyonuyla giriş bilgilerini alıyorum.
  def __init__(self):
    self.veri = {}

  # kullanıcının tc no, isim ve soyismini alarak kullanıcıya hesap açıyorum.
  def kullanici_ekle(self,tc,isim,soyisim):
    self.veri[tc] = {"isim":isim,"soyisim":soyisim}
    print(f"{isim} {soyisim} adlı kullanıcı eklenmiştir.")

  # kullanıcıların bilgileri listeliyorum.
  def kullanici_listele(self):
    for tc in self.veri:
      print(f"{tc} : {self.veri[tc]['isim']} {self.veri[tc]['soyisim']}")

  # kullanıcının tc nosu ile harcamalarını sisteme giriyorum.
  def harcama_ekle(self, tc,harcamalar):
    self.veri[tc] = {"isim":self.veri[tc]["isim"],
                     "soyisim":self.veri[tc]["soyisim"],
                     "harcama":harcamalar}
    print(f"{self.veri[tc]['isim']} adlı kullanıcının {harcamalar} harcaması kaydedilmiştir.")

  # kullanıcının harcama ortalamasını alıyorum.
  def harcama_ortalama(self, tc):
    harcama_listesi = self.veri[tc]["harcama"]
    ortalama = sum(harcama_listesi)/len(harcama_listesi)
    print(f"{self.veri[tc]['isim']} adlı kullanıcının ortalama harcaması {ortalama:.2f} TL'dir.")

  def kullanici_giris_ekrani(self):
    tc = int(input("TC numaranızı giriniz:"))
    if tc in self.veri.keys():
        if self.veri[tc]["isim"] is not None:
          print(f"Hoşgeldiniz {self.veri[tc]['isim']} {self.veri[tc]['soyisim']}")
          if self.veri[tc]["harcama"] is not None:
            self.harcama_ortalama(tc)
          else:
            harcamalar = []
            i=0
            while i<=3:
              harcama = int(input("Harcamayı giriniz:"))
              harcamalar.append(harcama)
              i+=1
            self.harcama_ekle(tc,harcamalar)
            print("Harcamalarınız eklendi, lütfen tekrar giriş yapınız.")
            kullanici_giris_ekrani()
        else:
          isim = input("İsminizi giriniz:")
          soyisim = input("Soyisminizi giriniz:")
          self.kullanici_ekle(tc,isim,soyisim)
    else:
      tc = input("Tc numaranızı giriniz:")
      isim = input("İsminizi giriniz:")
      soyisim = input("Soyisminizi giriniz:")
      harcamalar = []
      i=0
      while i<=3:
        harcama = int(input("Harcamayı giriniz:"))
        harcamalar.append(harcama)
        i+=1
      self.kullanici_ekle(tc,isim,soyisim)
      self.harcama_ekle(tc,harcamalar)
      print("Harcamalarınız eklendi, lütfen tekrar giriş yapınız.")
      self.kullanici_giris_ekrani()




In [81]:
garanti = banka()

In [82]:
garanti.kullanici_ekle(5168984,"Eren","Gemici")

Eren Gemici adlı kullanıcı eklenmiştir.


In [83]:
garanti.harcama_ekle(5168984,[18956,168984,5157968])

Eren adlı kullanıcının [18956, 168984, 5157968] harcaması kaydedilmiştir.


In [84]:
garanti.harcama_ortalama(5168984)

Eren adlı kullanıcının ortalama harcaması 1781969.33 TL'dir.


In [85]:
garanti.kullanici_giris_ekrani()

TC numaranızı giriniz:156516
Tc numaranızı giriniz:156168
İsminizi giriniz:Ahmet
Soyisminizi giriniz:Çallık 
Harcamayı giriniz:56
Harcamayı giriniz:26
Harcamayı giriniz:45
Harcamayı giriniz:35
Ahmet Çallık  adlı kullanıcı eklenmiştir.
Ahmet adlı kullanıcının [56, 26, 45, 35] harcaması kaydedilmiştir.
Harcamalarınız eklendi, lütfen tekrar giriş yapınız.
TC numaranızı giriniz:156168
Tc numaranızı giriniz:1561668


KeyboardInterrupt: Interrupted by user